before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: GyF0uZIdGxQp9wICQzPTM39kPmfNiMneS4cdge0iGOmzNuvvv04O30df+yc2lWI7QbMwfof+p5Aa1cxufmIm+XvC1I+q/8IiCDVKSVd7AqDNI2zlhHi8DD+mXtPnI1PaidnDCKMCJBYMRxqqT0neQqn+o0+0Su+dmpyd0ZGXuWkoO6XzV33qp2IqcaxiHrpdS+QOhPVEiX26Mqkg0+Fqp8tLRqxw2s784DGAqFMl012AtzeCp0K6LmmFHuJ4kW0Xr01ofWQxoVv8fwFGcgudmESF8roWePUMfAkNl4tsOpagW5hMRvT1dcHZdz9j5KjA/azssZf+MxliFPCXFUcwzumeq5rr+IqQaH0mTJ9cy6IYcqlsY82ny0gUxIgTEXyDF6Ok2pzUoP22jC8IXgUmjVZZZdqAMFsoo4BKaWveoA6/dpN+YGFTgGW6eqf/jfsfM/8xskPy7xHXMFCin5mIuMUxooDwU+i2XnPQy2npZ6fEz8SSrfU/ZYTx8pVv9zfASHid3srS+aWETY6h4+2g/LUiFHcV6+jTUYvL/dK1gyLgx+SS09eNxPmkOl/X5NWK5NPy5SObjTtDDfC2Qf/UqOszuiaWnf6CWQv8tsiKPHgPiA7Q3pCC874gL8kWg/6b0Cn7T+2Phqfeoz9/Aa6K91+dMwzi8hCXoy1TfYBaZSA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
